export const cities = [
  "London",
  "Birmingham",
  "Manchester",
  "Leeds",
  "Glasgow",
  "Sheffield",
  "Liverpool",
  "Bristol",
  "Edinburgh",
  "Leicester",
  "Coventry",
  "Newcastle upon Tyne",
  "Kingston upon Hull",
  "Cardiff",
  "Bradford",
  "Portsmouth",
  "Sunderland",
  "Nottingham",
  "Derby",
  "Plymouth",
  "Southampton",
  "Belfast",
  "Stoke-on-Trent",
  "Wolverhampton",
  "Aberdeen",
  "Dundee",
  "Swansea",
  "Newport",
  "Luton",
  "Oxford",
  "Sheffield",
  "Reading",
  "Blackpool",
  "Middlesbrough",
  "Oldham",
  "Bolton",
  "Stockport",
  "Brighton and Hove",
  "Preston",
  "Norwich",
  "Milton Keynes",
  "Sunderland",
  "Gloucester",
  "Saint Albans",
  "Hereford",
  "Lichfield",
  "Wakefield",
  "Salford",
  "Chester",
  "Lincoln",
  "Canterbury",
  "Lancaster",
  "Carlisle",
  "Ripon",
  "Chichester",
  "Wells",
  "Durham",
  "Lichfield",
  "Bangor",
  "Saint Asaph",
  "Newry",
  "Armagh",
  "Lisburn",
  "Londonderry",
  "Carlisle",
  "Perth",
  "Stirling",
  "Inverness",
  "Aberdeen",
  "Dundee",
  "Edinburgh",
  "Glasgow",
];

export const mockWeatherData = {
  city: {
    id: 2643743,
    name: "London",
    country: "GB",
  },
  coord: {
    lat: 51.5073,
    lon: -0.1276,
  },
  country: "GB",
  id: 2643743,
  name: "London",
  population: 1000000,
  sunrise: 1717559170,
  sunset: 1717618336,
  timezone: 3600,
  cnt: 40,
  cod: "200",
  list: [
    {
      dt: 1717578000,
      visibility: 10000,
      pop: 0,
      clouds: { all: 5 },
      dt_txt: "2024-06-05 09:00:00",
      main: {
        temp: 286.84,
        feels_like: 285.88,
        temp_min: 286.84,
        temp_max: 289.64,
        temp_kf: -1.87,
      },
      weather: [{ id: 800, main: "Clear", description: "clear sky" }],
      wind: { speed: 4.02, deg: 280, gust: 5.82 },
    },
  ],
};
