export const cities = [
  "London",
  "Birmingham",
  "Manchester",
  "Leeds",
  "Glasgow",
  "Sheffield",
  "Liverpool",
  "Bristol",
  "Edinburgh",
  "Leicester",
  "Coventry",
  "Newcastle upon Tyne",
  "Kingston upon Hull",
  "Cardiff",
  "Bradford",
  "Portsmouth",
  "Sunderland",
  "Nottingham",
  "Derby",
  "Plymouth",
  "Southampton",
  "Belfast",
  "Stoke-on-Trent",
  "Wolverhampton",
  "Aberdeen",
  "Dundee",
  "Swansea",
  "Newport",
  "Luton",
  "Oxford",
  "Sheffield",
  "Reading",
  "Blackpool",
  "Middlesbrough",
  "Oldham",
  "Bolton",
  "Stockport",
  "Brighton and Hove",
  "Preston",
  "Norwich",
  "Milton Keynes",
  "Sunderland",
  "Gloucester",
  "Saint Albans",
  "Hereford",
  "Lichfield",
  "Wakefield",
  "Salford",
  "Chester",
  "Lincoln",
  "Canterbury",
  "Lancaster",
  "Carlisle",
  "Ripon",
  "Chichester",
  "Wells",
  "Durham",
  "Lichfield",
  "Bangor",
  "Saint Asaph",
  "Newry",
  "Armagh",
  "Lisburn",
  "Londonderry",
  "Carlisle",
  "Perth",
  "Stirling",
  "Inverness",
  "Aberdeen",
  "Dundee",
  "Edinburgh",
  "Glasgow",
];
